monitor=eDP-1, 1920x1080@60, 0x0, 1

$terminal = kitty
$fileManager = kitty yazi
$menu = rofi -show drun -modes "drun,calc"
$browser = zen-browser

exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal-gtk
exec-once = awww-daemon
exec-once = waybar
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Adwaita-dark

source = ~/.config/hypr/custom/*
