monitor = desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545, 2560x1440@60, 0x0, 1

monitor = desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004, 1920x1080@60, 320x1440, 1

workspace = 1, monitor:desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004, default:true, persistent:true
workspace = 2, monitor:desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004
workspace = 3, monitor:desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004
workspace = 4, monitor:desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004
workspace = 5, monitor:desc:InfoVision Optoelectronics (Kunshan) Co.Ltd China 0x8596 0x00000004
workspace = 6, monitor:desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545, default:true, persistent:true
workspace = 7, monitor:desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545
workspace = 8, monitor:desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545
workspace = 9, monitor:desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545
workspace = 10, monitor:desc:Philips Consumer Electronics Company PHL 272B8Q UK01933010545
